export default [
  { label: 'ASI', value: 'ASI' },
  { label: 'BBIBOLL', value: 'BBIBOLL' },
  { label: 'BIAS', value: 'BIAS' },
  { label: 'BOLL', value: 'BOLL' },
  { label: 'CCI', value: 'CCI' },
  { label: 'CDP', value: 'CDP' },
  { label: 'DMA', value: 'DMA' },
  { label: 'DMI', value: 'DMI' },
  //{ label: 'EMA', value: 'EMA' },
  { label: 'EMV', value: 'EMV' },
  { label: 'KDJ', value: 'KDJ' },
  //{ label: 'MA', value: 'MA' },
  //{ label: 'MACD', value: 'MACD' },
  { label: 'MTM', value: 'MTM' },
  { label: 'OBV', value: 'OBV' },
  { label: 'ROC', value: 'ROC' },
  { label: 'RSI', value: 'RSI' },
  //{ label: 'SAR', value: 'SAR' },
  { label: 'TRIX', value: 'TRIX' },
  { label: 'VR', value: 'VR' },
  { label: 'WR', value: 'WR' },
  { label: 'WVAD', value: 'WVAD' },
]