export default [
  { label: 'ASI', value: 'ASI' },
  { label: 'BBIBOLL', value: 'BBIBOLL' },
  { label: 'BIAS', value: 'BIAS' },
  { label: 'BOLL', value: 'BOLL' },
  { label: 'CCI', value: 'CCI' },
  { label: 'CDP', value: 'CDP' },
  { label: 'DMA', value: 'DMA' },
  { label: 'DMI', value: 'DMI' },
  { label: 'EMA', value: 'EMA', disabled: true },
  { label: 'EMV', value: 'EMV' },
  { label: 'ENE', value: 'ENE' },
  { label: 'KDJ', value: 'KDJ' },
  { label: 'MA', value: 'MA', disabled: true },
  { label: 'MACD', value: 'MACD', disabled: true },
  { label: 'MTM', value: 'MTM' },
  { label: 'OBV', value: 'OBV' },
  { label: 'OSC', value: 'OSC'},
  { label: 'ROC', value: 'ROC' },
  { label: 'RSI', value: 'RSI' },
  { label: 'SAR', value: 'SAR', disabled: true},
  { label: 'TRIX', value: 'TRIX'},
  { label: 'VR', value: 'VR'},
  { label: 'WR', value: 'WR'},
  { label: 'WVAD', value: 'WVAD'},
]